### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by davidnoelopez** [ktgow/dmx_serial_sender#1]
I'm planning on making a lighting project, and I want to use addressable LED Strips. So I was looking for a way to receive a DMX signal on an arduino or Raspberry pi, and with that signal trigger different programs to control the LED strips, so I can have 256 option to trigger different lightning setups. So my question is if this can be posible with this code?

**Comment by ktgow** [comment]
Yes, that's almost exactly what I used this for.

A few things to note: The code in this project is very timing-specific.  It works on an Arduino Uno, and it should work on any Arduino that runs at the same speed, but I haven't tested other boards.  I had an Arduino Uno dedicated to reading the DMX signal (using this program), and then it fed the information to another board (another Arduino in my case, but it could be a Raspberry Pi or something else).  The other board ran the light show.

Also note that this is made for the CTC-DRA-10-1 DMX Shield.  That's what the DMX controller plugs into, and that's what provides the input for this program.

**Comment by davidnoelopez** [comment]
Thanks for your response! I got here by [this tutorial](http://playground.arduino.cc/Learning/DMX) but it looks like that they don't sell the CTC-DRA-10-1 DMX Shield. ~~Do you know where I can get it?~~ nvm I found it [here](https://www.tindie.com/products/Conceptinetics/dmx-shield-for-arduino-rdm-capable/). Thanks Again!

**Comment by ktgow** [comment]
Glad you found it.  That's exactly the same link I was about to send you.  :)
